name: meandra
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Data manipulation and formats
  - numpy
  - pandas                 # data frames
  - xarray                 # labeled arrays and datasets
  - netCDF4                # for saving data with xarray
  - pyyaml                 # YAML file handling
  - types-pyyaml           # type stubs for Pyyaml
  # Configuration and file handling
  - omegaconf              # configuration management tool
  # Development tools
  - black                  # code formatting
  - mypy                   # static type checking
  - mypy_extensions
  - pylint                 # code linting
  - pyright                # code linting
  # Testing
  - pytest
  - pytest-mock
  - pytest-pylint          # Pylint plugin for Pytest
  # Documentation
  - sphinx                 # documentation generator
  - sphinxcontrib-napoleon # for numpydoc-style docstrings
  - sphinx-rtd-theme       # ReadTheDocs theme
  - sphinx-needs           # for requirements and specifications in Sphinx
  - esbonio                # language server for Sphinx
variables:
